name: Build ARM64 Docker Images
on:
  schedule:
    # TODO: only run daily
    - cron: '*/30 * * * *'

jobs:
  build-images:
    runs-on: [self-hosted, linux, ARM64]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout heighliner
        uses: actions/checkout@v2

      - name: Build heighliner
        run: go build

      - name: Build and push images
        run: ./heighliner build -r ghcr.io/strangelove-ventures/heighliner -n 1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
