name: Build and Push CosmosHub Docker Image

on:
  push:
    tags:
      - "cosmoshub-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  INFRA_TOOLKIT: v0.1.6

jobs:
  build-and-push-cosmoshub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Heighliner binary
        run: |
          go build -o heighliner

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/cosmoshub-}" >> $GITHUB_ENV

      - name: Manually pull the base Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/p2p-org/cosmos-heighliner:cosmoshub-v18.1.0

      - name: Pull gaiad binary
        run: |
          cd temp/
          wget https://github.com/cosmos/gaia/releases/download/v19.1.0/gaiad-v19.1.0-linux-amd64

      - name: Build and push cosmoshub Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          cd temp/
          docker build -t gaia:${{ env.VERSION }} .

      - name: Tag and push Docker image
        run: |
          docker tag gaia:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cosmoshub-${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cosmoshub-${{ env.VERSION }}
